// vue/src/context/tictactoe/components/Board/index.vue
<template>
  <div>
    <div class="board">
      <div class="board-row" v-for="(v, i) in edgeLength">
        <Square v-for="(v, j) in edgeLength"
          :key="'square-' + ((edgeLength * i) + j)"
          :value="squares[((edgeLength * i) + j)]"
          @onClick="$emit('onClick', (edgeLength * i) + j)"
        />
      </div>
    </div>
  </div>
</template>

<script>
import Square from '../Square'
import './Board'

export default {
  name: "Board",
  props: {
    squares: Array,
    xIsNext: Boolean,
    player: String
  },
  computed: {
    edgeLength: function() {
      return Math.sqrt(this.squares.length)
    }
  },
  components: {
    Square 
  }
}
</script>

// react/src/context/tictactoe/components/Board/index.jsx
import React, { Component } from 'react';
import Square from '../Square';
import './Board';

class Board extends Component {
  renderSquare(i) {
    const key = `square-${i}`;
    return (
      <Square
        key={key}
        value={this.props.squares[i]}
        onClick={() => this.props.onClick(i)}
      />
    );
  }

  renderRowSquares(edgeLength, rowNum) {
    const add = edgeLength * rowNum;
    const row = [];
    for (let i = 0; i < edgeLength; i++) {
      row.push(this.renderSquare(i + add))
    }
    return row;
  }

  render() {
    const edgeLength = Math.sqrt(this.props.squares.length);
    let rows = [];
    for (let i = 0; i < edgeLength; i++) {
      const key = `row-${i}`;
      rows.push(<div className="board-row" key={key}>{this.renderRowSquares(edgeLength, i)}</div>);
    }
    return (
      <div>
        {rows}
      </div>
    );
  }
}

export default Board;
